services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    restart: unless-stopped
  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT}:6379"
    restart: unless-stopped

volumes:
  pgdata: